<a href="https://colab.research.google.com/github/deboratech/7DaysOfCode/blob/main/1DaysOfCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

## **Coleta dos dados**

In [5]:
dados_2010_1 = pd.read_csv('/content/emprestimos-20101.csv')
dados_2010_2 = pd.read_csv('/content/emprestimos-20102.csv')
dados_2011_1 = pd.read_csv('/content/emprestimos-20111.csv')
dados_2011_2 = pd.read_csv('/content/emprestimos-20112.csv')
dados_2012_1 = pd.read_csv('/content/emprestimos-20121.csv')
dados_2012_2 = pd.read_csv('/content/emprestimos-20122.csv')
dados_2013_1 = pd.read_csv('/content/emprestimos-20131.csv')
dados_2013_2 = pd.read_csv('/content/emprestimos-20132.csv')
dados_2014_1 = pd.read_csv('/content/emprestimos-20141.csv')
dados_2014_2 = pd.read_csv('/content/emprestimos-20142.csv')
dados_2015_1 = pd.read_csv('/content/emprestimos-20151.csv')
dados_2015_2 = pd.read_csv('/content/emprestimos-20152.csv')
dados_2016_1 = pd.read_csv('/content/emprestimos-20161.csv')
dados_2016_2 = pd.read_csv('/content/emprestimos-20162.csv')
dados_2017_1 = pd.read_csv('/content/emprestimos-20171.csv')
dados_2017_2 = pd.read_csv('/content/emprestimos-20172.csv')
dados_2018_1 = pd.read_csv('/content/emprestimos-20181.csv')
dados_2018_2 = pd.read_csv('/content/emprestimos-20182.csv')
dados_2019_1 = pd.read_csv('/content/emprestimos-20191.csv')
dados_2019_2 = pd.read_csv('/content/emprestimos-20192.csv')
dados_2020_1 = pd.read_csv('/content/emprestimos-20201.csv')

## **Concatenando os DataFrames**

In [6]:
emprestimos_biblioteca = [dados_2010_2, dados_2010_1, dados_2011_1, dados_2011_2, dados_2012_1, dados_2012_2, dados_2013_1, dados_2013_2, dados_2014_1, dados_2014_2, dados_2015_1, dados_2015_2, dados_2016_1, dados_2016_2, dados_2017_1, dados_2017_2, dados_2018_1, dados_2018_2, dados_2019_1, dados_2019_2, dados_2020_1]

In [7]:
emprestimos_biblioteca = pd.concat(emprestimos_biblioteca)

In [8]:
emprestimos_biblioteca

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,799100,S025602_19/11/2013 10:51:34,NaN,2010/07/01 07:45:41.111000000,2010/07/07 10:52:31.000000000,2.009050e+09,ALUNO DE GRADUAÇÃO
1,799101,2008049500,NaN,2010/07/01 08:08:17.690000000,2010/07/01 09:03:44.000000000,2.010056e+09,ALUNO DE GRADUAÇÃO
2,799102,X008043,NaN,2010/07/01 08:13:31.574000000,2010/07/09 15:14:44.000000000,2.009043e+09,ALUNO DE GRADUAÇÃO
3,799103,2009055438,2010/07/14 18:35:35.042000000,2010/07/01 08:22:46.085000000,2010/07/29 14:59:16.000000000,2.009054e+09,ALUNO DE GRADUAÇÃO
4,799104,S024636,2010/07/16 21:29:43.569000000,2010/07/01 08:40:28.512000000,2010/07/28 07:49:32.000000000,2.009054e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
26556,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
26557,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
26558,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
26559,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
26560,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

## **Verificando informações sobre o DataFrame**

In [9]:
emprestimos_biblioteca.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2258018 entries, 0 to 26560
Data columns (total 7 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
dtypes: float64(1), int64(1), object(5)
memory usage: 137.8+ MB

## **Verificando dados duplicados**

In [17]:
emprestimos_biblioteca.value_counts()

id_emprestimo  codigo_barras  data_renovacao                 data_emprestimo                data_devolucao                 matricula_ou_siape  tipo_vinculo_usuario
709686         2006017618     2010/01/26 08:07:01.738000000  2010/01/04 08:08:44.081000000  2010/02/25 07:36:25.800000000  2.008112e+09        ALUNO DE PÓS-GRADUAÇÃO    1
2336122        2011033079     2016/11/21 02:01:58.488000000  2016/11/10 17:00:12.989000000  2016/12/02 14:21:49.000000000  2.016023e+09        ALUNO DE GRADUAÇÃO        1
2336103        2014085936     2016/11/25 19:25:36.215000000  2016/11/10 16:54:52.447000000  2016/12/13 14:30:52.000000000  2.014047e+09        ALUNO DE GRADUAÇÃO        1
2336104        2011027960     2016/11/23 17:27:54.642000000  2016/11/10 16:55:17.956000000  2016/11/28 10:32:38.000000000  2.016083e+09        ALUNO DE GRADUAÇÃO        1
2336105        2014000897     2016/12/02 15:02:53.356000000  2016/11/10 16:55:19.851000000  2016/12/23 13:53:23.000000000  2.014071e+09        ALUNO DE GRADUAÇÃO        1
                                                                                                                                                                        ..
1443383        2010043058     2013/03/21 14:06:09.837000000  2013/03/07 11:17:25.008000000  2013/03/22 11:31:20.000000000  2.010023e+09        ALUNO DE GRADUAÇÃO        1
1443387        L147018        2013/03/21 19:43:42.047000000  2013/03/07 11:20:01.159000000  2013/04/04 10:50:22.000000000  2.013053e+09        ALUNO DE GRADUAÇÃO        1
1443389        2011018954     2013/03/22 13:18:55.037000000  2013/03/07 11:21:26.480000000  2013/04/08 20:26:07.000000000  2.010046e+09        ALUNO DE GRADUAÇÃO        1
1443390        2009056314     2013/03/21 09:28:45.689000000  2013/03/07 11:21:28.899000000  2013/04/05 18:18:00.000000000  2.011015e+09        ALUNO DE GRADUAÇÃO        1
10322328       2014070441     2018/01/15 12:26:00.697000000  2017/12/29 18:21:09.060000000  2018/01/31 18:50:25.000000000  2.014063e+09        ALUNO DE GRADUAÇÃO        1
Name: count, Length: 968028, dtype: int64

In [18]:
duplicados = emprestimos_biblioteca.duplicated()

In [19]:
duplicados.sum()

0

## **Excluindo dados duplicados**

In [15]:
emprestimos_biblioteca = emprestimos_biblioteca.drop_duplicates()

## **Verificando dados nulos**

In [20]:
emprestimos_biblioteca.isnull().sum()

id_emprestimo                 0
codigo_barras                 0
data_renovacao          1285709
data_emprestimo               0
data_devolucao             6471
matricula_ou_siape         3170
tipo_vinculo_usuario          0
dtype: int64

## **Importando dados exemplares**

In [21]:
dados_exemplares = pd.read_parquet('/dados_exemplares.parquet')

## **Verificando informações do DataFrame**

In [22]:
dados_exemplares.info()

<class 'pandas.core.frame.DataFrame'>
Index: 546237 entries, 0 to 568584
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_exemplar       546237 non-null  int64
 1   codigo_barras     546237 non-null  object
 2   colecao           546237 non-null  object
 3   biblioteca        546237 non-null  object
 4   status_material   546237 non-null  object
 5   localizacao       546237 non-null  int64
 6   registro_sistema  546237 non-null  int64
dtypes: int64(3), object(4)
memory usage: 33.3+ MB

## **Verificando dados duplicados**

In [24]:
dados_exemplares.value_counts()

id_exemplar  codigo_barras  colecao            biblioteca                                             status_material  localizacao  registro_sistema
3            L000001        Acervo Circulante  Biblioteca Central Zila Mamede                         ESPECIAL         638          1                   1
1070480      2013071582     Acervo Circulante  Biblioteca Setorial do Centro Ciências da Saúde - CCS  REGULAR          340          200283              1
1070506      2013077711     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          354          200288              1
1070505      2013077710     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          327          200288              1
1070504      2013077807     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          348          200286              1
                                                                                                                                                       ..
232120       2007034699     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          652          96457               1
232119       2007034703     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          628          96456               1
232118       2007036783     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          618          96301               1
232117       2007040275     Acervo Circulante  Biblioteca Central Zila Mamede                         REGULAR          680          96301               1
1353476      2019012276     Acervo Circulante  Biblioteca Central Zila Mamede                         ESPECIAL         962          268236              1
Name: count, Length: 546237, dtype: int64

In [26]:
duplicados_dados_exemplares = dados_exemplares.duplicated()
duplicados_dados_exemplares.sum()

0

## **Verificando dados nulos**

In [28]:
dados_exemplares.isnull().sum()

id_exemplar         0
codigo_barras       0
colecao             0
biblioteca          0
status_material     0
localizacao         0
registro_sistema    0
dtype: int64

## **Unindo os DataFrames**

In [29]:
emprestimos_completos = pd.merge(emprestimos_biblioteca, dados_exemplares)

In [30]:
emprestimos_completos

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,799100,S025602_19/11/2013 10:51:34,NaN,2010/07/01 07:45:41.111000000,2010/07/07 10:52:31.000000000,2.009050e+09,ALUNO DE GRADUAÇÃO,186525,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,635,71668
1,809804,S025602_19/11/2013 10:51:34,2010/08/10 20:36:21.378000000,2010/08/09 14:32:14.211000000,2010/08/30 17:04:59.000000000,2.008035e+09,ALUNO DE GRADUAÇÃO,186525,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,635,71668
2,826521,S025602_19/11/2013 10:51:34,NaN,2010/08/30 17:06:09.807000000,2010/09/03 08:13:44.000000000,2.008035e+09,ALUNO DE GRADUAÇÃO,186525,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,635,71668
3,831124,S025602_19/11/2013 10:51:34,NaN,2010/09/08 11:07:07.699000000,2010/09/15 07:34:37.000000000,2.007343e+08,ALUNO DE GRADUAÇÃO,186525,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,635,71668
4,839249,S025602_19/11/2013 10:51:34,NaN,2010/09/17 10:47:36.670000000,2010/10/05 16:33:03.000000000,2.009054e+09,ALUNO DE GRADUAÇÃO,186525,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,635,71668
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2072517,2989018,2009036492,NaN,2020/03/17 19:49:10.187000000,2020/12/03 08:12:20.000000000,2.015011e+10,ALUNO DE GRADUAÇÃO,274820,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,676,120845
2072518,2989020,2014062640,NaN,2020/03/17 19:51:15.700000000,2021/01/07 11:16:28.000000000,2.019004e+10,ALUNO DE GRADUAÇÃO,1157915,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,228,213248
2072519,2989032,2018003324,NaN,2020/03/17 20:00:11.416000000,2021/08/30 13:29:44.000000000,2.019102e+10,ALUNO DE PÓS-GRADUAÇÃO,1317173,Acervo Circulante,Biblioteca Setorial da Faculdade de Ciências d...,REGULAR,784,255835
2072520,2989049,2006024313,NaN,2020/03/17 20:47:18.741000000,NaN,2.015013e+10,ALUNO DE GRADUAÇÃO,206073,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,663,82178
2072521,2989061,2018031352,NaN,2020/03/17 21:22:22.138000000,2021/07/26 15:05:20.000000000,2.020001e+10,ALUNO DE GRADUAÇÃO,1342535,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,355,174443

## **Verificando informações do DataFrame**

In [31]:
emprestimos_completos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2072522 entries, 0 to 2072521
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   id_emprestimo         int64
 1   codigo_barras         object
 2   data_renovacao        object
 3   data_emprestimo       object
 4   data_devolucao        object
 5   matricula_ou_siape    float64
 6   tipo_vinculo_usuario  object
 7   id_exemplar           int64
 8   colecao               object
 9   biblioteca            object
 10  status_material       object
 11  localizacao           int64
 12  registro_sistema      int64
dtypes: float64(1), int64(4), object(8)
memory usage: 205.6+ MB